cc_library(
    name = 'evhtp',
    srcs = [
        'evhtp.c',
        'evthr.c',
        'htparse.c',
    ],
    deps = [
        '//thirdparty/libevent:event'
    ],
    extra_cppflags = '-Wno-strict-aliasing'
)

